# scripts/ember/run_extended_kernels_grid.py
"""
Driver for the extended-kernels + probabilistic-classifier experiments over
the paper's 18-setting grid (workstream B of the manuscript expansion).

Assumes master splits and q-splits already exist (they are generated by
scripts/analysis/run_kernel_geometry_grid.py or by the paper orchestrator).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Tuple

PAPER_SIZES: List[Tuple[int, int, int]] = [(1000, 500, 500), (2000, 1000, 1000), (4000, 1800, 1800)]
DEFAULT_VARIANTS = ["m1_hist_byteent", "m2_hist_byteent"]
DEFAULT_MASTER_SEEDS = [42, 123, 999]
DEFAULT_DIMS = [4, 6, 8, 10, 12]


def run(cmd: List[str], log_path: Path) -> None:
    print(f"[CMD] {' '.join(cmd)}")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as f:
        f.write(f"\n[CMD] {' '.join(cmd)}\n")
        f.flush()
        p = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT)
    if p.returncode != 0:
        tail = "".join(log_path.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)[-30:])
        raise RuntimeError(f"Command failed (exit {p.returncode}). Log tail:\n{tail}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits-root", type=Path, default=Path("data/processed/ember"))
    ap.add_argument("--out-root", type=Path, default=Path("results/ember_shift/extended_kernels"))
    ap.add_argument("--log-dir", type=Path, default=Path("results/ember_shift/extended_kernels/_logs"))
    ap.add_argument("--variants", nargs="+", default=DEFAULT_VARIANTS)
    ap.add_argument("--master-seeds", nargs="+", type=int, default=DEFAULT_MASTER_SEEDS)
    ap.add_argument("--qsplit-seeds", nargs="+", type=int, default=[42])
    ap.add_argument("--model-seeds", nargs="+", type=int, default=[42])
    ap.add_argument("--dims", nargs="+", type=int, default=DEFAULT_DIMS)
    ap.add_argument("--sizes", nargs="+", default=[f"{a},{b},{c}" for a, b, c in PAPER_SIZES])
    ap.add_argument("--rbf-gamma-factors", nargs="+", type=float, default=[])
    ap.add_argument("--quantum-angle-scales", nargs="+", type=float, default=[])
    args = ap.parse_args()

    sizes = [tuple(int(x) for x in s.split(",")) for s in args.sizes]
    py = sys.executable
    t_start = time.time()
    n_done = 0

    for variant in args.variants:
        for ms in args.master_seeds:
            hits = sorted(args.splits_root.glob(f"splits_sparsity__{variant}__ms{ms}__h*"))
            if len(hits) != 1:
                raise RuntimeError(f"Expected one master dir for {variant}/ms{ms}, found {hits}")
            qsplits_root = hits[0] / "qsplits"

            for (n_train, n_id, n_ood) in sizes:
                for qs in args.qsplit_seeds:
                    qdir = qsplits_root / f"splits_sparsity_q{n_train}_id{n_id}_ood{n_ood}_seed{qs}"
                    if not (qdir / "train_idx.npy").exists():
                        raise RuntimeError(f"Missing q-split (run the geometry grid driver first): {qdir}")

                    for mseed in args.model_seeds:
                        label = f"{variant}__ms{ms}__q{n_train}_id{n_id}_ood{n_ood}__qs{qs}__s{mseed}"
                        out_dir = args.out_root / label
                        if (out_dir / "extended_kernels_qsplits__summary.csv").exists():
                            print(f"[SKIP] {label}")
                            n_done += 1
                            continue

                        t0 = time.time()
                        cmd = [py, "-m", "src.experiments.ember.extended.run_ember_extended_kernels_qsplits",
                               "--splits-dir", str(qdir),
                               "--out-dir", str(out_dir),
                               "--seed", str(mseed),
                               "--dims", *[str(d) for d in args.dims],
                               "--include-quantum",
                               "--mmap"]
                        if args.rbf_gamma_factors:
                            cmd += ["--rbf-gamma-factors", *[f"{f:g}" for f in args.rbf_gamma_factors]]
                        if args.quantum_angle_scales:
                            cmd += ["--quantum-angle-scales", *[f"{s:g}" for s in args.quantum_angle_scales]]
                        run(cmd, args.log_dir / f"extended__{label}.log")
                        n_done += 1
                        print(f"[OK] {label} in {time.time() - t0:.0f}s "
                              f"({n_done} done, {(time.time() - t_start) / 60:.1f} min total)")

    print(f"[✓] Extended grid complete: {n_done} combos in {(time.time() - t_start) / 60:.1f} min")


if __name__ == "__main__":
    main()
